# Use an official OpenJDK runtime as a parent image
FROM adoptopenjdk:20

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container at the specified directory
COPY target/housemanagement.jar /app/housemanagement.jar

# Expose a port (if your Spring Boot app listens on a specific port)
EXPOSE 8080

# Specify the command to run your application
CMD ["java", "-jar", "housemanagement.jar"]
